language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - composer self-update

install:
    - composer install

script:
    - ./vendor/bin/phpunit -c phpunit.xml.dist

after_script:
    - php ./vendor/bin/coveralls -v
