version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        depends_on:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    php:
        image: merorafael/php-fpm:7.0
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/symfony_app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini