services:
    api.directory_builder:
        class: ApiBundle\FileManager\DirectoryBuilder
        arguments: ['%edi_baseuri%', '%edi_dir%', '%edi_orderdir%']

    api.file_manager:
        class: ApiBundle\FileManager\FileManager
        arguments: ['@api.directory_builder']

    api.json_request_listener:
        class: ApiBundle\EventListener\JsonRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }